<?php
/**
 * Utils general config
 */

/*
 * -----------------------------------------------------------------------------
 *  [!] NOTICE
 * -----------------------------------------------------------------------------
 *
 *  If you need to make modifications to the default configuration,
 *  copy this file to your 'app/config' folder, and make them in there.
 *
 *  This will allow you to upgrade FuelPHP without losing your custom config.
 *
 */

return [
    /*
     * -------------------------------------------------------------------------
     *  Base URL
     * -------------------------------------------------------------------------
     *
     *  The base URL of the application.
     *
     *  You can set this to a full or relative URL:
     *
     *      'base_url' => '/foo/',
     *      'base_url' => 'http://foo.com/'
     *
     *  It MUST contain a trailing slash (/).
     *
     *  Set this to null to have it automatically detected.
     *
     */

    'base_url' => null,

    /*
     * -------------------------------------------------------------------------
     *  URL Suffix
     * -------------------------------------------------------------------------
     *
     *  Any suffix that needs to be added to URL's generated by Fuel.
     *  If the suffix is an extension, make sure to include the dot.
     *
     *      'url_suffix' => '.html',
     *
     *  Set this to an empty string if no suffix is used.
     *
     */

    'url_suffix' => '',

    /*
     * -------------------------------------------------------------------------
     *  Errors
     * -------------------------------------------------------------------------
     */

    'errors' => [
        /*
         * ---------------------------------------------------------------------
         *  Behavior
         * ---------------------------------------------------------------------
         *
         *  Which errors should we show, but continue execution? You can add
         *  the following:
         *
         *      E_NOTICE, E_WARNING, E_DEPRECATED, E_STRICT
         *
         *  to mimic PHP's default behaviour (which is to continue
         *  on non-fatal errors). We consider this bad practice.
         *
         */

        'continue_on' => [],

        /*
         * ---------------------------------------------------------------------
         *  Throttling
         * ---------------------------------------------------------------------
         *
         *  How many errors should we show before we stop showing them?
         *
         *  [!] INFO:
         *
         *  This is useful to prevents out-of-memory errors.
         *
         */

        'throttle' => 10,

        /*
         * ---------------------------------------------------------------------
         *  Notification
         * ---------------------------------------------------------------------
         *
         *  Should notices from Error::notice() be shown?
         *
         */

        'notices' => true,
    ],

    /*
     * -------------------------------------------------------------------------
     *  Language - Default
     * -------------------------------------------------------------------------
     */

    'language' => 'en',

    /*
     * -------------------------------------------------------------------------
     *  Language - Fallback
     * -------------------------------------------------------------------------
     *
     *  Fallback language when file isn't available for default language.
     *
     */

    'language_fallback' => 'en',

    /*
     * -------------------------------------------------------------------------
     *  Language - Locale
     * -------------------------------------------------------------------------
     *
     *  PHP set_locale() setting. Use null to not set.
     *
     */

    'locale' => 'en_US',

    /*
     * -------------------------------------------------------------------------
     *  Language - Character Encoding
     * -------------------------------------------------------------------------
     *
     *  Internal string encoding charset.
     *
     */

    'encoding' => 'UTF-8',

    /*
     * -------------------------------------------------------------------------
     *  DateTime - Time Zone
     * -------------------------------------------------------------------------
     *
     *  Change the server's default timezone. This is optional.
     *
     */

    'default_timezone' => null,

    /*
     * -------------------------------------------------------------------------
     *  Log - Threshold
     * -------------------------------------------------------------------------
     *
     *  Can be set to any of the following:
     *
     *      Fuel::L_NONE
     *      Fuel::L_ERROR
     *      Fuel::L_WARNING
     *      Fuel::L_DEBUG
     *      Fuel::L_INFO
     *      Fuel::L_ALL
     *
     */

    'log_threshold' => \Fuel::L_WARNING,

    /*
     * -------------------------------------------------------------------------
     *  Log - Settings
     * -------------------------------------------------------------------------
     *
     *  Log file and path will be generated if the value is not provided or null
     *
     */

    'log_file' => null,
    'log_path' => APPPATH . 'logs' . DS,

    'log_date_format' => 'Y-m-d H:i:s',

    /*
     * -------------------------------------------------------------------------
     *  CLI Backtrace
     * -------------------------------------------------------------------------
     *
     *  If true, a backtrace is printed when a PHP fatal error is encountered
     *  in CLI mode.
     *
     */

    'cli_backtrace' => false,

    /*
     * -------------------------------------------------------------------------
     *  Security
     * -------------------------------------------------------------------------
     */

    'security' => [
        /*
         * ---------------------------------------------------------------------
         *  X-Headers
         * ---------------------------------------------------------------------
         *
         *  Allow the Input class to use X headers when present.
         *
         *  Examples of these are:
         *
         *      HTTP_X_FORWARDED_FOR and HTTP_X_FORWARDED_PROTO
         *
         *  which can be faked which could have security implications.
         *
         */

        'allow_x_headers' => false,

        /*
         * ---------------------------------------------------------------------
         *  HTML Entities - Encoding Mode
         * ---------------------------------------------------------------------
         *
         *  Encoding mechanism to use on htmlentities().
         *
         */

        'htmlentities_flags' => ENT_QUOTES,

        /*
         * ---------------------------------------------------------------------
         *  HTML Entities - Encoding Method
         * ---------------------------------------------------------------------
         *
         *  Whether to encode HTML entities as well.
         *
         */

        'htmlentities_double_encode' => false,

        /*
         * ---------------------------------------------------------------------
         *  HTML Entities - Auto Filter
         * ---------------------------------------------------------------------
         *
         *  Whether to automatically filter view data.
         *
         */

        'auto_filter_output' => true,

        /*
         * ---------------------------------------------------------------------
         *  Closures
         * ---------------------------------------------------------------------
         *
         *  Whether to filter closures as well.
         *
         */

        'filter_closures' => true,

        /*
         * ---------------------------------------------------------------------
         *  Class Whitelist
         * ---------------------------------------------------------------------
         *
         *  With output encoding switched on, all objects passed will be
         *  converted to strings or throw exceptions unless they are instances
         *  of the classes in this array.
         *
         */

        'whitelisted_classes' => [],

        /*
         * ---------------------------------------------------------------------
         *  Form - URL Encoding
         * ---------------------------------------------------------------------
         *
         *  Set this to true if your client sends data using these HTTP methods:
         *
         *      PUT, DELETE or PATCH
         *
         *  and using the 'www-form-urlencoded' content type and its content is
         *  urlencoded locally before submitted.
         *
         */

        'form-double-urlencoded' => false,

        /*
         * ---------------------------------------------------------------------
         *  Path Cleaning
         * ---------------------------------------------------------------------
         *
         *  Paths to clean before outputting FQFN or paths.
         *
         *  If you do not wish to see the path, set this to 'null'.
         *  You can also add other paths that you wish not to see.
         *
         */

        'clean_paths' => [],
    ],

    /*
     * -------------------------------------------------------------------------
     *  Validation
     * -------------------------------------------------------------------------
     */

    'validation' => [
        /*
         * ---------------------------------------------------------------------
         *  Compatibility
         * ---------------------------------------------------------------------
         *
         *  Whether falling back to global when a value is not found
         *  in input array.
         *
         */

        'global_input_fallback' => true,
    ],

    /*
     * -------------------------------------------------------------------------
     *  Configurations
     * -------------------------------------------------------------------------
     */

    'config' => [
        /*
         * ---------------------------------------------------------------------
         *  Database
         * ---------------------------------------------------------------------
         *
         *  Database that holds the config table.
         *
         */

        'database' => null,

        /*
         * ---------------------------------------------------------------------
         *  Database - Table Name
         * ---------------------------------------------------------------------
         *
         *  Name of the table used by the Config_Db driver.
         *
         */

        'table_name' => 'config',

        /*
         * ---------------------------------------------------------------------
         *  Memcached
         * ---------------------------------------------------------------------
         *
         *  Servers and port numbers that run the memcached service
         *  for config data.
         *
         */

        'memcached'	=> [
            'identifier' => 'config',

            'servers' => [
                [
                    'host'   => '127.0.0.1',
                    'port'   => 11211,
                    'weight' => 100,
                ],
            ],
        ],
    ],

    /*
     * -------------------------------------------------------------------------
     *  Language
     * -------------------------------------------------------------------------
     */

    'lang' => [
        // Database that holds the lang table
        'database' => null,

        // Name of the table used by the Lang_Db driver
        'table_name' => 'lang',
    ],

    /*
     * -------------------------------------------------------------------------
     *  Always load
     * -------------------------------------------------------------------------
     */

    'always_load' => [

        /*
         * ---------------------------------------------------------------------
         *  Configurations
         * ---------------------------------------------------------------------
         *
         *  Configurations to autoload
         *
         *  If you want to load 'session' config into a group 'session',
         *  you only have to add 'session'.
         *
         *      'config' => array('session')
         *
         *  If you want to add it to another group (example: 'auth'),
         *  you have to add it like:
         *
         *      'config' => array('session' => 'auth')
         *
         *  If you don't want the config in a group, use null as groupname.
         *
         */

        'config' => [],

        /*
         * ---------------------------------------------------------------------
         *  Languages
         * ---------------------------------------------------------------------
         *
         *  Language files to autoload
         *
         *  If you want to load 'validation' lang into a group 'validation',
         *  you only have to add 'validation'.
         *
         *      'language' => array('validation')
         *
         *  If you want to add it to another group (example: 'forms'),
         *  you have to add it like:
         *
         *      'language' => array('validation' => 'forms')
         *
         *  If you don't want the lang in a group, use null as groupname.
         *
         */

        'language' => [],
    ],
];
